jvm_highcore_task:
  only_if: $CIRRUS_TAG != '' || $CIRRUS_PR != ''
  required_pr_labels: Cirrus JVM
  container:
    image: sbtscala/scala-sbt:eclipse-temurin-jammy-17.0.5_8_1.9.0_3.3.0
    cpu: 8
    memory: 16G
  matrix:
    - name: JVM high-core-count 2.13
      script: sbt '++ 2.13' testsJVM/test ioAppTestsJVM/test
    - name: JVM high-core-count 3
      script: sbt '++ 3' testsJVM/test ioAppTestsJVM/test
